-- TEAM - 14 SNOWFLAKE PROJECT 
--THEJITH YADAV & MUKESH 
-- VEHICLE SERVICE ANALYTICS
-- Database : VEHICLE_SERVICE_DB
-- Schema   : SERVICE_ANALYTICS


-- 1. OVERALL PROJECT DATA 

SELECT
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT VEHICLE_ID) AS TOTAL_VEHICLES,
    COUNT(DISTINCT SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST,
    ROUND(AVG(TOTAL_SERVICE_COST), 2) AS AVERAGE_SERVICE_COST
FROM SERVICE_ANALYTICS;


-- 2. CUSTOMER SERVICE ANALYSIS
-- Shows number of services and total service cost by customer

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    COUNT(SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST
FROM SERVICE_ANALYTICS
GROUP BY
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY
ORDER BY TOTAL_SERVICE_COST DESC;


-- 3. VEHICLE SERVICE COST ANALYSIS
-- Identifies vehicles with the highest service expenditure


SELECT
    VEHICLE_ID,
    REGISTRATION_NUMBER,
    MAKE,
    MODEL,
    CUSTOMER_NAME,
    COUNT(SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST
FROM SERVICE_ANALYTICS
GROUP BY
    VEHICLE_ID,
    REGISTRATION_NUMBER,
    MAKE,
    MODEL,
    CUSTOMER_NAME
ORDER BY TOTAL_SERVICE_COST DESC;


-- 4. SERVICE TYPE ANALYSIS
-- Compares service frequency and cost by service type

SELECT
    SERVICE_TYPE,
    COUNT(SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST,
    ROUND(AVG(TOTAL_SERVICE_COST), 2) AS AVERAGE_SERVICE_COST
FROM SERVICE_ANALYTICS
GROUP BY SERVICE_TYPE
ORDER BY TOTAL_SERVICES DESC;


-- 5. PARTS USAGE ANALYSIS
-- Identifies the most frequently used vehicle parts
-- Inspection services are excluded because they have no parts

SELECT
    PART_ID,
    PART_NAME,
    CATEGORY,
    SUPPLIER_NAME,
    SUM(QUANTITY) AS TOTAL_QUANTITY_USED,
    COUNT(SERVICE_ID) AS SERVICES_USING_PART,
    SUM(UNIT_COST * QUANTITY) AS TOTAL_PART_COST
FROM SERVICE_ANALYTICS
WHERE PART_ID IS NOT NULL
GROUP BY
    PART_ID,
    PART_NAME,
    CATEGORY,
    SUPPLIER_NAME
ORDER BY TOTAL_QUANTITY_USED DESC;


-- 6. SUPPLIER ANALYSIS
-- Shows part usage and expenditure by supplier

SELECT
    SUPPLIER_NAME,
    COUNT(DISTINCT PART_ID) AS NUMBER_OF_PARTS,
    SUM(QUANTITY) AS TOTAL_QUANTITY_USED,
    SUM(UNIT_COST * QUANTITY) AS TOTAL_PART_COST
FROM SERVICE_ANALYTICS
WHERE PART_ID IS NOT NULL
GROUP BY SUPPLIER_NAME
ORDER BY TOTAL_PART_COST DESC;


-- 7. SERVICE STATUS ANALYSIS
-- Shows service count and cost according to service status

SELECT
    SERVICE_STATUS,
    COUNT(SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST,
    ROUND(AVG(TOTAL_SERVICE_COST), 2) AS AVERAGE_SERVICE_COST
FROM SERVICE_ANALYTICS
GROUP BY SERVICE_STATUS
ORDER BY TOTAL_SERVICES DESC;


-- 8. MONTHLY SERVICE TREND
-- Shows service activity and cost over time

SELECT
    DATE_TRUNC('MONTH', SERVICE_DATE) AS SERVICE_MONTH,
    COUNT(SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST,
    ROUND(AVG(TOTAL_SERVICE_COST), 2) AS AVERAGE_SERVICE_COST
FROM SERVICE_ANALYTICS
GROUP BY DATE_TRUNC('MONTH', SERVICE_DATE)
ORDER BY SERVICE_MONTH;


-- 9. TIME TRAVEL
-- performing the time travel operations 

-- View the current data
SELECT *
FROM SERVICE_HISTORY
LIMIT 10;

--update query 
UPDATE SERVICE_HISTORY SET QUANTITY = 2 WHERE SERVICE_ID = 'SRV001';

-- Retrieve the table as it existed 5 minutes ago
SELECT *
FROM SERVICE_HISTORY
AT (OFFSET => -60 * 5)
LIMIT 10;


-- 10. ZERO-COPY CLONING
-- Creates a clone of the SERVICE_HISTORY table
-- without initially duplicating the underlying data

CREATE OR REPLACE TABLE SERVICE_HISTORY_CLONE
CLONE SERVICE_HISTORY;


-- Verify the cloned table
SELECT *
FROM SERVICE_HISTORY_CLONE
LIMIT 10;


-- Verify the number of records
SELECT COUNT(*) AS CLONE_RECORD_COUNT
FROM SERVICE_HISTORY_CLONE;