CREATE DATABASE VEHICLE_SERVICE_DB;

CREATE SCHEMA VEHICLE_SERVICE_DB.SERVICE_ANALYTICS;

USE DATABASE VEHICLE_SERVICE_DB;

USE SCHEMA SERVICE_ANALYTICS;
--CUSTOMERS TABLE--
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID      VARCHAR(10)  PRIMARY KEY,
    CUSTOMER_NAME    VARCHAR(100),
    PHONE            VARCHAR(20),
    EMAIL            VARCHAR(100),
    CITY             VARCHAR(50)
);

DESC TABLE CUSTOMERS;
--VEHICLES TABLE--
CREATE OR REPLACE TABLE VEHICLES (
    VEHICLE_ID           VARCHAR(10)  PRIMARY KEY,
    CUSTOMER_ID          VARCHAR(10),
    REGISTRATION_NUMBER  VARCHAR(20),
    MAKE                 VARCHAR(50),
    MODEL                VARCHAR(50),
    MANUFACTURING_YEAR   NUMBER(4),
    VEHICLE_TYPE         VARCHAR(30)
);

DESC TABLE VEHICLES;
--PARTS TABLE--
CREATE OR REPLACE TABLE PARTS (
    PART_ID        VARCHAR(10)   PRIMARY KEY,
    PART_NAME      VARCHAR(100),
    CATEGORY       VARCHAR(50),
    UNIT_COST      NUMBER(10,2),
    SUPPLIER_NAME  VARCHAR(100)
);

DESC TABLE PARTS;
--SERVICE_HISTORY TABLE--
CREATE OR REPLACE TABLE SERVICE_HISTORY (
    SERVICE_ID      VARCHAR(10)  PRIMARY KEY,
    VEHICLE_ID      VARCHAR(10),
    SERVICE_DATE    DATE,
    SERVICE_TYPE    VARCHAR(50),
    PART_ID         VARCHAR(10),
    QUANTITY        NUMBER(10,0),
    LABOR_COST      NUMBER(10,2),
    SERVICE_STATUS  VARCHAR(30)
);

DESC TABLE SERVICE_HISTORY;
