-- CREATION OF FILE FORMAT OBJECT--
CREATE OR REPLACE FILE FORMAT VEHICLE_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('');

    --stage creation--
    CREATE OR REPLACE STAGE VEHICLE_S3_STAGE
    URL = 's3://snowflake-project-nsic/SnowFlake_project/'
    CREDENTIALS = (
        AWS_KEY_ID = '*****************'
        AWS_SECRET_KEY = '***************'
    )
    FILE_FORMAT = VEHICLE_CSV_FORMAT;
    
--listing VEHICLE_S3_STAGE  stage items--

LIST @VEHICLE_S3_STAGE;
--DESCRIPTION OF STAGE--
DESC STAGE VEHICLE_S3_STAGE;

--testing stage--
SELECT $1, $2, $3
FROM @VEHICLE_S3_STAGE/customers.csv
(FILE_FORMAT => VEHICLE_CSV_FORMAT)
LIMIT 5;

--tables creation--
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(20),
    CUSTOMER_NAME VARCHAR(100),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    CITY VARCHAR(50)
);

CREATE OR REPLACE TABLE PARTS (
    PART_ID VARCHAR(20),
    PART_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_COST NUMBER(10,2),
    SUPPLIER_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE VEHICLES (
    VEHICLE_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    REGISTRATION_NUMBER VARCHAR(30),
    MAKE VARCHAR(50),
    MODEL VARCHAR(50),
    MANUFACTURING_YEAR NUMBER(4,0),
    VEHICLE_TYPE VARCHAR(30)
);

CREATE OR REPLACE TABLE SERVICE_HISTORY (
    SERVICE_ID VARCHAR(20),
    VEHICLE_ID VARCHAR(20),
    SERVICE_DATE DATE,
    SERVICE_TYPE VARCHAR(100),
    PART_ID VARCHAR(20),
    QUANTITY NUMBER(10,0),
    LABOR_COST NUMBER(10,2),
    SERVICE_STATUS VARCHAR(30)
);

COPY INTO CUSTOMERS
FROM @VEHICLE_S3_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = VEHICLE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
select * from customers;

COPY INTO PARTS
FROM @VEHICLE_S3_STAGE/parts.csv
FILE_FORMAT = (FORMAT_NAME = VEHICLE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
select * from parts;

COPY INTO VEHICLES
FROM @VEHICLE_S3_STAGE/vehicles.csv
FILE_FORMAT = (FORMAT_NAME = VEHICLE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
select * from vehicles;

COPY INTO SERVICE_HISTORY
FROM @VEHICLE_S3_STAGE/service_history.csv
FILE_FORMAT = (FORMAT_NAME = VEHICLE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';
select * from service_history;

--verification of total records--
SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CUSTOMERS
UNION ALL
SELECT 'PARTS', COUNT(*) FROM PARTS
UNION ALL
SELECT 'VEHICLES', COUNT(*) FROM VEHICLES
UNION ALL
SELECT 'SERVICE_HISTORY', COUNT(*) FROM SERVICE_HISTORY;

--relationship checklist--
SELECT
    v.VEHICLE_ID,
    v.REGISTRATION_NUMBER,
    c.CUSTOMER_NAME,
    sh.SERVICE_ID,
    p.PART_NAME,
    sh.QUANTITY,
    sh.LABOR_COST,
    sh.SERVICE_STATUS
FROM VEHICLES v
JOIN CUSTOMERS c
    ON v.CUSTOMER_ID = c.CUSTOMER_ID
JOIN SERVICE_HISTORY sh
    ON v.VEHICLE_ID = sh.VEHICLE_ID
LEFT JOIN PARTS p
    ON sh.PART_ID = p.PART_ID
ORDER BY v.VEHICLE_ID, sh.SERVICE_DATE;

--Calculating Total Service Cost--
SELECT
    sh.SERVICE_ID,
    sh.VEHICLE_ID,
    sh.SERVICE_DATE,
    sh.SERVICE_TYPE,
    p.PART_NAME,
    COALESCE(sh.QUANTITY, 0) AS QUANTITY,
    COALESCE(p.UNIT_COST, 0) AS UNIT_COST,
    sh.LABOR_COST,
    (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0) AS TOTAL_SERVICE_COST,
    sh.SERVICE_STATUS
FROM SERVICE_HISTORY sh
LEFT JOIN PARTS p
    ON sh.PART_ID = p.PART_ID
ORDER BY sh.SERVICE_DATE;

--Customer Service Summary--
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    COUNT(sh.SERVICE_ID) AS TOTAL_SERVICES,
    SUM(
        (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0)
    ) AS TOTAL_SERVICE_COST
FROM CUSTOMERS c
JOIN VEHICLES v
    ON c.CUSTOMER_ID = v.CUSTOMER_ID
JOIN SERVICE_HISTORY sh
    ON v.VEHICLE_ID = sh.VEHICLE_ID
LEFT JOIN PARTS p
    ON sh.PART_ID = p.PART_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_SERVICE_COST DESC;

--vehicle-level maintenance analysis---
SELECT
    v.VEHICLE_ID,
    v.REGISTRATION_NUMBER,
    v.MAKE,
    v.MODEL,
    c.CUSTOMER_NAME,
    COUNT(sh.SERVICE_ID) AS TOTAL_SERVICES,
    SUM(
        (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0)
    ) AS TOTAL_SERVICE_COST
FROM VEHICLES v
JOIN CUSTOMERS c
    ON v.CUSTOMER_ID = c.CUSTOMER_ID
JOIN SERVICE_HISTORY sh
    ON v.VEHICLE_ID = sh.VEHICLE_ID
LEFT JOIN PARTS p
    ON sh.PART_ID = p.PART_ID
GROUP BY
    v.VEHICLE_ID,
    v.REGISTRATION_NUMBER,
    v.MAKE,
    v.MODEL,
    c.CUSTOMER_NAME
ORDER BY TOTAL_SERVICE_COST DESC;

--most used part--
SELECT
    p.PART_ID,
    p.PART_NAME,
    p.CATEGORY,
    p.SUPPLIER_NAME,
    SUM(sh.QUANTITY) AS TOTAL_QUANTITY_USED,
    COUNT(sh.SERVICE_ID) AS SERVICES_USING_PART,
    SUM(p.UNIT_COST * sh.QUANTITY) AS TOTAL_PART_COST
FROM PARTS p
JOIN SERVICE_HISTORY sh
    ON p.PART_ID = sh.PART_ID
GROUP BY
    p.PART_ID,
    p.PART_NAME,
    p.CATEGORY,
    p.SUPPLIER_NAME
ORDER BY TOTAL_QUANTITY_USED DESC;

--Supplier Cost Analysis--
SELECT
    p.SUPPLIER_NAME,
    COUNT(DISTINCT p.PART_ID) AS NUMBER_OF_PARTS,
    SUM(sh.QUANTITY) AS TOTAL_QUANTITY_SUPPLIED,
    SUM(p.UNIT_COST * sh.QUANTITY) AS TOTAL_PART_COST
FROM PARTS p
JOIN SERVICE_HISTORY sh
    ON p.PART_ID = sh.PART_ID
GROUP BY p.SUPPLIER_NAME
ORDER BY TOTAL_PART_COST DESC;

--Service Status Analysis--
SELECT
    SERVICE_STATUS,
    COUNT(*) AS TOTAL_SERVICES,
    SUM(
        (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0)
    ) AS TOTAL_SERVICE_COST,
    AVG(
        (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0)
    ) AS AVERAGE_SERVICE_COST
FROM SERVICE_HISTORY sh
LEFT JOIN PARTS p
    ON sh.PART_ID = p.PART_ID
GROUP BY SERVICE_STATUS
ORDER BY TOTAL_SERVICES DESC;

--Service-Type Analysis--
SELECT
    sh.SERVICE_TYPE,
    COUNT(*) AS TOTAL_SERVICES,
    SUM(
        (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0)
    ) AS TOTAL_SERVICE_COST,
    AVG(
        (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0)
    ) AS AVERAGE_SERVICE_COST
FROM SERVICE_HISTORY sh
LEFT JOIN PARTS p
    ON sh.PART_ID = p.PART_ID
GROUP BY sh.SERVICE_TYPE
ORDER BY TOTAL_SERVICES DESC;

--duplicate records verification--
SELECT CUSTOMER_ID, COUNT(*) AS CNT
FROM CUSTOMERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

SELECT VEHICLE_ID, COUNT(*) AS CNT
FROM VEHICLES
GROUP BY VEHICLE_ID
HAVING COUNT(*) > 1;

SELECT sh.SERVICE_ID, sh.VEHICLE_ID
FROM SERVICE_HISTORY sh
LEFT JOIN VEHICLES v
    ON sh.VEHICLE_ID = v.VEHICLE_ID
WHERE v.VEHICLE_ID IS NULL;
--done verification successfully--


--creating a view for better analysis--
CREATE OR REPLACE VIEW SERVICE_ANALYTICS AS
SELECT
    sh.SERVICE_ID,
    sh.SERVICE_DATE,
    sh.SERVICE_TYPE,
    sh.SERVICE_STATUS,

    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY,

    v.VEHICLE_ID,
    v.REGISTRATION_NUMBER,
    v.MAKE,
    v.MODEL,
    v.MANUFACTURING_YEAR,
    v.VEHICLE_TYPE,

    sh.PART_ID,
    p.PART_NAME,
    p.CATEGORY,
    p.SUPPLIER_NAME,

    COALESCE(sh.QUANTITY, 0) AS QUANTITY,
    COALESCE(p.UNIT_COST, 0) AS UNIT_COST,
    COALESCE(sh.LABOR_COST, 0) AS LABOR_COST,

    (COALESCE(p.UNIT_COST, 0) * COALESCE(sh.QUANTITY, 0))
        + COALESCE(sh.LABOR_COST, 0) AS TOTAL_SERVICE_COST

FROM SERVICE_HISTORY sh

JOIN VEHICLES v
    ON sh.VEHICLE_ID = v.VEHICLE_ID

JOIN CUSTOMERS c
    ON v.CUSTOMER_ID = c.CUSTOMER_ID

LEFT JOIN PARTS p
    ON sh.PART_ID = p.PART_ID;

--verifying view--
SELECT *
FROM SERVICE_ANALYTICS
LIMIT 100;

--mini dashboard query--
SELECT
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT VEHICLE_ID) AS TOTAL_VEHICLES,
    COUNT(DISTINCT SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST,
    AVG(TOTAL_SERVICE_COST) AS AVERAGE_SERVICE_COST
FROM SERVICE_ANALYTICS;