--TOP 5 VEHICLES BY SERVICE COST--
SELECT
    VEHICLE_ID,
    REGISTRATION_NUMBER,
    MAKE,
    MODEL,
    CUSTOMER_NAME,
    TOTAL_SERVICE_COST
FROM SERVICE_ANALYTICS
ORDER BY TOTAL_SERVICE_COST DESC
LIMIT 5;

--SERVICE COST BY SERVICE TYPE--
SELECT
    SERVICE_TYPE,
    COUNT(*) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_COST,
    AVG(TOTAL_SERVICE_COST) AS AVERAGE_COST
FROM SERVICE_ANALYTICS
GROUP BY SERVICE_TYPE
ORDER BY TOTAL_COST DESC;

--PARTS USAGE--
SELECT
    PART_ID,
    PART_NAME,
    CATEGORY,
    SUPPLIER_NAME,
    SUM(QUANTITY) AS TOTAL_QUANTITY_USED,
    SUM(UNIT_COST * QUANTITY) AS TOTAL_PART_COST
FROM SERVICE_ANALYTICS
WHERE PART_ID IS NOT NULL
GROUP BY
    PART_ID,
    PART_NAME,
    CATEGORY,
    SUPPLIER_NAME
ORDER BY TOTAL_QUANTITY_USED DESC;

--FINAL CHECK--
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA();
SHOW TABLES;
SHOW VIEWS;


SELECT
    (SELECT COUNT(*) FROM CUSTOMERS) AS CUSTOMERS,
    (SELECT COUNT(*) FROM PARTS) AS PARTS,
    (SELECT COUNT(*) FROM VEHICLES) AS VEHICLES,
    (SELECT COUNT(*) FROM SERVICE_HISTORY) AS SERVICE_RECORDS,
    (SELECT COUNT(*) FROM SERVICE_ANALYTICS) AS ANALYTICS_RECORDS;

--VIEW CHECKING--
SELECT * FROM SERVICE_ANALYTICS;

--Monthly Service Trend--
SELECT
    DATE_TRUNC('MONTH', SERVICE_DATE) AS SERVICE_MONTH,
    COUNT(*) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST,
    AVG(TOTAL_SERVICE_COST) AS AVERAGE_SERVICE_COST
FROM SERVICE_ANALYTICS
GROUP BY DATE_TRUNC('MONTH', SERVICE_DATE)
ORDER BY SERVICE_MONTH;

--CUSTOMER LIFETIME SERVICE VALUE--
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    COUNT(DISTINCT VEHICLE_ID) AS VEHICLES_OWNED,
    COUNT(DISTINCT SERVICE_ID) AS TOTAL_SERVICES,
    SUM(TOTAL_SERVICE_COST) AS TOTAL_SERVICE_COST,
    ROUND(AVG(TOTAL_SERVICE_COST), 2) AS AVG_SERVICE_COST
FROM SERVICE_ANALYTICS
GROUP BY
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY
ORDER BY TOTAL_SERVICE_COST DESC;